# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_direction', models.IntegerField(blank=True, default=0)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
