# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_winddata_wind_gust'),
    ]

    operations = [
        migrations.AddField(
            model_name='winddata',
            name='variable_wind_direction_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='winddata',
            name='variable_wind_direction_min',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
