# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirBudConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_dwell_time_min', models.DurationField(default=datetime.timedelta(0, 0, 10000))),
                ('carrier_dwell_time_max', models.DurationField(default=datetime.timedelta(0, 2))),
                ('carrier_interval_time_min', models.DurationField(default=datetime.timedelta(0, 0, 100000))),
                ('carrier_interval_time_max', models.DurationField(default=datetime.timedelta(0, 2))),
                ('weather_check_clicks', models.IntegerField(default=4)),
                ('transmission_check_clicks', models.IntegerField(default=3)),
                ('report_gust', models.IntegerField(default=3)),
                ('report_variable_winds', models.IntegerField(default=15)),
                ('update_direction', models.IntegerField(default=30)),
                ('update_speed', models.IntegerField(default=5)),
                ('update_timer', models.IntegerField(default=5)),
                ('cross_wind_limit_speed', models.IntegerField(default=6)),
                ('cross_wind_limit_direction', models.IntegerField(default=45)),
                ('favor_wind_speed', models.IntegerField(default=6)),
                ('favor_wind_direction', models.IntegerField(default=44)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
