# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirBudConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_dwell_time', models.DurationField(default=datetime.timedelta(0, 2, 50000))),
                ('data_check_clicks', models.IntegerField(default=4)),
                ('transmission_check_clicks', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
